AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Description: S3 Deployment Layer
Parameters:
  DeploymentBucketName:
    Type: String
  DeploymentKey:
    Type: String

Resources:
  S3DeploymentLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
      Description: S3 Deployment Layer
      LayerName: !Ref AWS::StackName
      LicenseInfo: MIT
      ContentUri:
        Bucket: !Ref DeploymentBucketName
        Key: !Ref DeploymentKey
      RetentionPolicy: Retain

  DeploymentPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref S3DeploymentLayer
      Principal: '*'

Outputs:
  Arn: 
    Value: !Ref S3DeploymentLayer
